import type { OpeningEntry } from "./types";

/**
 * ECO opening database — common openings mapped by SAN move sequence.
 * Sorted by move sequence length (longest first) for longest prefix match.
 */
export const ECO_DATABASE: OpeningEntry[] = [
  { moves: "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O", name: "Ruy Lopez: Closed", eco: "C84" },
  { moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6", name: "Sicilian Najdorf", eco: "B90" },
  { moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6", name: "Sicilian Dragon", eco: "B70" },
  { moves: "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6", name: "King's Indian Defense: Classical", eco: "E70" },
  { moves: "d4 d5 c4 c6 Nf3 Nf6 Nc3 e6", name: "Semi-Slav Defense", eco: "D43" },
  { moves: "d4 d5 Nf3 Nf6 c4 e6 Nc3 Be7", name: "Queen's Gambit Declined: Orthodox", eco: "D60" },
  { moves: "e4 c6 d4 d5 Nc3 dxe4 Nxe4", name: "Caro-Kann: Classical", eco: "B18" },
  { moves: "e4 c5 Nf3 d6 d4 cxd4 Nxd4", name: "Sicilian Defense: Open", eco: "B32" },
  { moves: "e4 e6 d4 d5 exd5 exd5", name: "French Defense: Exchange", eco: "C01" },
  { moves: "d4 Nf6 c4 c5 d5 e6", name: "Modern Benoni", eco: "A60" },
  { moves: "Nf3 Nf6 c4 g6 g3 Bg7", name: "English Opening: King's Indian", eco: "A15" },
  { moves: "e4 d6 d4 Nf6 Nc3 g6", name: "Pirc Defense: Classical", eco: "B08" },
  { moves: "d4 Nf6 c4 g6 Nc3 d5", name: "Grunfeld Defense", eco: "D80" },
  { moves: "e4 e5 Nf3 Nc6 Bb5 a6", name: "Ruy Lopez: Morphy Defense", eco: "C65" },
  { moves: "e4 e5 Nf3 Nc6 Bc4 Bc5", name: "Italian Game: Giuoco Piano", eco: "C53" },
  { moves: "e4 e5 Nf3 Nc6 Bc4 Nf6", name: "Italian Game: Two Knights Defense", eco: "C55" },
  { moves: "d4 Nf6 c4 e6 Nc3 d5", name: "Queen's Gambit Declined", eco: "D30" },
  { moves: "d4 Nf6 c4 g6 Nc3 Bg7", name: "King's Indian Defense", eco: "E60" },
  { moves: "d4 Nf6 c4 e6 Nc3 Bb4", name: "Nimzo-Indian Defense", eco: "E20" },
  { moves: "d4 Nf6 c4 e6 Nf3 b6", name: "Queen's Indian Defense", eco: "E15" },
  { moves: "d4 Nf6 Nf3 g6 c4 Bg7", name: "King's Indian Defense", eco: "E60" },
  { moves: "e4 e5 Nf3 Nc6 Bb5", name: "Ruy Lopez", eco: "C60" },
  { moves: "e4 e5 Nf3 Nc6 Bc4", name: "Italian Game", eco: "C50" },
  { moves: "e4 e5 Nf3 Nc6 d4", name: "Scotch Game", eco: "C45" },
  { moves: "e4 e6 d4 d5 Nc3", name: "French Defense: Winawer", eco: "C15" },
  { moves: "e4 e6 d4 d5 Nd2", name: "French Defense: Tarrasch", eco: "C03" },
  { moves: "e4 e6 d4 d5 e5", name: "French Defense: Advance", eco: "C02" },
  { moves: "e4 c6 d4 d5 e5", name: "Caro-Kann: Advance", eco: "B12" },
  { moves: "d4 d5 Nf3 Nf6 Bf4", name: "London System", eco: "D00" },
  { moves: "e4 c5 Nf3 Nc6", name: "Sicilian Defense: Old Sicilian", eco: "B30" },
  { moves: "e4 c5 Nf3 e6", name: "Sicilian Defense: French Variation", eco: "B40" },
  { moves: "e4 e5 Nf3 Nc6", name: "King's Knight Opening", eco: "C40" },
  { moves: "e4 e5 Nf3 Nf6", name: "Petrov's Defense", eco: "C42" },
  { moves: "e4 e5 Nf3 d6", name: "Philidor Defense", eco: "C41" },
  { moves: "d4 d5 c4 e6", name: "Queen's Gambit Declined", eco: "D30" },
  { moves: "d4 d5 c4 dxc4", name: "Queen's Gambit Accepted", eco: "D20" },
  { moves: "d4 d5 c4 c6", name: "Slav Defense", eco: "D10" },
  { moves: "d4 Nf6 c4 e6 g3", name: "Catalan Opening", eco: "E01" },
  { moves: "d4 Nf6 c4 c5", name: "Benoni Defense", eco: "A56" },
  { moves: "Nf3 d5 c4", name: "Reti Opening", eco: "A09" },
  { moves: "c4 e5", name: "English Opening: Reversed Sicilian", eco: "A20" },
  { moves: "c4 c5", name: "English Opening: Symmetrical", eco: "A30" },
  { moves: "c4 Nf6", name: "English Opening: Anglo-Indian", eco: "A15" },
  { moves: "e4 e6 d4 d5", name: "French Defense", eco: "C00" },
  { moves: "e4 c6 d4 d5", name: "Caro-Kann Defense", eco: "B12" },
  { moves: "e4 e5 f4", name: "King's Gambit", eco: "C30" },
  { moves: "e4 e5 d4", name: "Center Game", eco: "C21" },
  { moves: "e4 e5 Nc3", name: "Vienna Game", eco: "C25" },
  { moves: "e4 c5 c3", name: "Sicilian Defense: Alapin", eco: "B22" },
  { moves: "d4 d5 Bf4", name: "London System", eco: "D00" },
  { moves: "d4 d5 c4", name: "Queen's Gambit", eco: "D06" },
  { moves: "Nf3 d5 g3", name: "King's Indian Attack", eco: "A07" },
  { moves: "Nf3 d5", name: "Reti Opening", eco: "A05" },
  { moves: "e4 e5", name: "King's Pawn Game", eco: "C20" },
  { moves: "e4 c5", name: "Sicilian Defense", eco: "B20" },
  { moves: "e4 e6", name: "French Defense", eco: "C00" },
  { moves: "e4 c6", name: "Caro-Kann Defense", eco: "B10" },
  { moves: "e4 d5", name: "Scandinavian Defense", eco: "B01" },
  { moves: "e4 d6", name: "Pirc Defense", eco: "B07" },
  { moves: "e4 g6", name: "Modern Defense", eco: "B06" },
  { moves: "e4 Nf6", name: "Alekhine's Defense", eco: "B02" },
  { moves: "d4 d5", name: "Queen's Pawn Game", eco: "D00" },
  { moves: "d4 Nf6", name: "Indian Defense", eco: "A45" },
  { moves: "d4 f5", name: "Dutch Defense", eco: "A80" },
  { moves: "c4", name: "English Opening", eco: "A10" },
  { moves: "Nf3", name: "Reti Opening", eco: "A04" },
  { moves: "g3", name: "Hungarian Opening", eco: "A00" },
  { moves: "b3", name: "Nimzo-Larsen Attack", eco: "A01" },
  { moves: "f4", name: "Bird's Opening", eco: "A02" },
];
