import { useState, useCallback } from 'react'
import ToolLayout from '../components/ToolLayout'
import useJumpToResult from '../hooks/useJumpToResult'
import useAIStream from '../hooks/useAIStream'

const CATEGORIES = [
  { id: 'any category', label: '🎲 Random', emoji: '' },
  { id: 'puns', label: '🔤 Puns', emoji: '' },
  { id: 'dad jokes', label: '👔 Dad Jokes', emoji: '' },
  { id: 'one-liners', label: '⚡ One-Liners', emoji: '' },
  { id: 'observations', label: '👀 Observations', emoji: '' },
  { id: 'tech humor', label: '💻 Tech', emoji: '' },
  { id: 'clean dark humor', label: '🌙 Dark (Clean)', emoji: '' },
]

const RATE_MSGS = { '😂': 'Glad you liked it! 😂', '😐': 'Fair enough, try another!', '🙄': 'Ouch! Dad jokes are an art form 😅' }

export default function ai_joke_generator() {
  const { ref: resultRef, jumpTo } = useJumpToResult()
  const { output, status, streaming, generate, stop } = useAIStream()
  const [category, setCategory] = useState('any category')
  const [copied, setCopied] = useState(false)
  const [rating, setRating] = useState('')

  const handleGenerate = useCallback(() => {
    setRating('')
    generate({
      messages: [{
        role: 'user',
        content: `Tell me one original ${category} joke. Format: Setup on first line, then punchline on the next line. Just the joke, no intro or explanation.`
      }],
      temperature: 1.0,
      systemPrompt: 'You are a stand-up comedian. Generate a single, original, funny joke. Keep it clean and appropriate for all ages unless specified. Be creative and surprising.',
    })
    jumpTo()
  }, [category, generate, jumpTo])

  const copy = () => {
    if (!output) return
    navigator.clipboard.writeText(output).then(() => {
      setCopied(true); setTimeout(() => setCopied(false), 1500)
    })
  }

  const share = () => {
    if (!output) return
    if (navigator.share) {
      navigator.share({ title: 'Funny Joke from UpTools', text: output, url: location.href })
    } else {
      navigator.clipboard.writeText(output)
      setCopied(true); setTimeout(() => setCopied(false), 1500)
    }
  }

  return (
    <ToolLayout
      title="AI Joke Generator"
      desc="Get original, funny jokes on demand. Choose a category — puns, dad jokes, tech humor, one-liners — and let AI deliver instant laughs."
      icon="😂" iconBg="rgba(245,158,11,0.08)"
      category="ai" slug="ai-joke-generator"
      faq={[
        { q: "Are the jokes AI-generated?", a: "Yes, each joke is freshly generated by AI — they're unique every time!" },
        { q: "Can I get clean jokes only?", a: "Yes, by default jokes are clean and family-friendly. Select 'Dark (Clean)' for edgier but still appropriate humor." },
      ]}
      howItWorks={[
        "Pick a joke category from the buttons above.",
        "Click Generate to get a fresh AI-written joke.",
        "Rate it with the emoji buttons or share it!",
      ]}
      schema={{
        "@context": "https://schema.org", "@type": "SoftwareApplication",
        "name": "AI Joke Generator", "applicationCategory": "EntertainmentApplication",
        "url": "https://www.uptools.in/ai-joke-generator/",
        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "INR" }
      }}
    >
      <div className="max-w-3xl mx-auto space-y-4">
        {/* Category Picker */}
        <div className="bg-white/[0.06] border border-white/[0.08] rounded-2xl p-4">
          <label className="block text-sm font-semibold text-slate-300 mb-3">Pick a Category</label>
          <div className="flex flex-wrap gap-2">
            {CATEGORIES.map(c => (
              <button key={c.id} onClick={() => setCategory(c.id)}
                className={`px-3 py-2 rounded-xl text-xs font-bold transition-all ${
                  category === c.id
                    ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                    : 'bg-white/[0.04] text-slate-500 border border-white/[0.08] hover:text-white'
                }`}>
                {c.label}
              </button>
            ))}
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-2 flex-wrap">
          {streaming ? (
            <button onClick={stop}
              className="flex-1 px-6 py-3 rounded-xl text-sm font-bold bg-red-500/20 text-red-400 border border-red-500/30 hover:bg-red-500/30 transition-all">
              ⏹ Stop
            </button>
          ) : (
            <button onClick={handleGenerate}
              className="flex-1 px-6 py-3 rounded-xl text-sm font-bold text-white transition-all active:scale-[0.98]"
              style={{ background: 'linear-gradient(135deg, #f59e0b, #d97706)' }}>
              😂 Generate Joke
            </button>
          )}
          <button onClick={copy} disabled={!output}
            className={`px-4 py-2 rounded-xl text-sm font-bold border transition-all disabled:opacity-40 ${copied ? 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30' : 'bg-white/[0.06] border-white/[0.08] text-slate-400 hover:text-white'}`}>
            {copied ? '✓ Copied' : '📋 Copy'}
          </button>
          <button onClick={share} disabled={!output}
            className="px-4 py-2 rounded-xl text-sm font-bold bg-white/[0.06] border border-white/[0.08] text-slate-400 hover:text-white transition-all disabled:opacity-40">
            🔗 Share
          </button>
        </div>

        {/* Rating */}
        {output && !streaming && (
          <div className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.04] border border-white/[0.08]">
            <span className="text-xs text-slate-500 font-semibold">Rate this joke:</span>
            {['😂', '😐', '🙄'].map(emoji => (
              <button key={emoji} onClick={() => setRating(emoji)}
                className={`text-xl transition-all hover:scale-125 ${rating === emoji ? 'scale-125' : 'opacity-60 hover:opacity-100'}`}>
                {emoji}
              </button>
            ))}
            {rating && <span className="text-xs text-slate-400 ml-2">{RATE_MSGS[rating]}</span>}
          </div>
        )}

        {/* Status */}
        {status && (
          <div className={`p-3 rounded-xl text-sm ${status.includes('Error') ? 'bg-red-500/10 border border-red-500/20 text-red-400' : 'bg-white/[0.06] border border-white/[0.08] text-slate-400'}`}>
            {status}
          </div>
        )}

        {/* Output */}
        <div ref={resultRef} className="bg-white/[0.06] border border-white/[0.08] rounded-2xl p-4">
          {output ? (
            <pre className="text-sm text-slate-300 whitespace-pre-wrap font-mono leading-relaxed">{output}</pre>
          ) : (
            <div className="text-center py-12">
              <div className="text-4xl mb-3 opacity-20">😂</div>
              <p className="text-sm text-slate-600 font-medium">Click Generate to get a joke!</p>
            </div>
          )}
        </div>
      </div>
    </ToolLayout>
  )
}
